version: '2'
services:
    seed:
        build: 
            context: .
            dockerfile: Dockerfile-seed
    db:
        image: mongo
        volumes_from: 
            - seed
        command: ["/seed/seed.sh"]
    descriptions:
        build: ./descriptions
        links: 
            - db
        ports:
            - "3000:3000"
    nutrients:
        build: ./nutrients
        links:
            - db
        ports:
            - "3001:3000"
    flask:
        build: ./flask
        expose:
            - "8000"
        links:
            - db
        env_file: .env
        volumes:
            - ./flask:/usr/src/app
        ports:
            - "8000:8000"
        command: "/usr/local/bin/gunicorn -w 2 -b 0.0.0.0:8000 app:app"
    ngbuild:
        build: ./frontend
        volumes:
            - ng2:/src/dist
    web:
        image: nginx 
        volumes:
            - ng2:/usr/share/nginx/html
        ports:
            - "80:80"
        depends_on:
            - descriptions
volumes:
    ng2: {}
